#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-unindent
Version  : 1.0
Release  : 6
URL      : https://rubygems.org/downloads/unindent-1.0.gem
Source0  : https://rubygems.org/downloads/unindent-1.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-nanotest
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc

%description
### Summary
Simple Ruby method, `String#unindent`, to unindent strings. Useful for
multi-line strings embeded in already indented code.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n unindent-1.0
gem spec %{SOURCE0} -l --ruby > rubygem-unindent.gemspec

%build
gem build rubygem-unindent.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
unindent-1.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/unindent-1.0 &&  rake --trace TESTOPTS="-v" && popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/unindent-1.0.gem
/usr/lib64/ruby/gems/2.2.0/doc/unindent-1.0/ri/String/cdesc-String.ri
/usr/lib64/ruby/gems/2.2.0/doc/unindent-1.0/ri/String/unindent%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/unindent-1.0/ri/String/unindent-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/unindent-1.0/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/gems/unindent-1.0/.gitignore
/usr/lib64/ruby/gems/2.2.0/gems/unindent-1.0/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/unindent-1.0/Manifest
/usr/lib64/ruby/gems/2.2.0/gems/unindent-1.0/README.md
/usr/lib64/ruby/gems/2.2.0/gems/unindent-1.0/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/unindent-1.0/examples.rb
/usr/lib64/ruby/gems/2.2.0/gems/unindent-1.0/lib/unindent.rb
/usr/lib64/ruby/gems/2.2.0/gems/unindent-1.0/specs.watchr
/usr/lib64/ruby/gems/2.2.0/gems/unindent-1.0/test/test_helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/unindent-1.0/test/test_unindent.rb
/usr/lib64/ruby/gems/2.2.0/gems/unindent-1.0/unindent.gemspec
/usr/lib64/ruby/gems/2.2.0/specifications/unindent-1.0.gemspec
